# fly.toml app configuration file generated for telenews-bot
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.

app = "telenews-bot"
primary_region = "nrt"  # Tokyo (일본 서버 - 가장 가까움)

[build]
  builder = "paketobuildpacks/builder:base"

[processes]
  app = "python bot.py"

[env]
  NEWS_CHECK_INTERVAL = "30"

# 텔레그램 봇은 HTTP 서버가 아니므로 services 섹션 제거
# [[services]] 섹션 불필요

[vm]
  memory = "256mb"
  cpu_kind = "shared"
  cpus = 1

